import SwiftUI
import AppKit

// MARK: - SF Symbol Database
// Comprehensive list of SF Symbols organized by category
// Based on SF Symbols 5+ with runtime validation

struct SFSymbolDatabase {

    /// Validates if a symbol exists on the current system
    static func symbolExists(_ name: String) -> Bool {
        NSImage(systemSymbolName: name, accessibilityDescription: nil) != nil
    }

    /// Returns validated symbols for a category (filters out unavailable symbols)
    static func validatedSymbols(for category: String) -> [SFSymbolOption] {
        guard let symbols = allCategories[category] else { return [] }
        return symbols.filter { symbolExists($0) }.map { SFSymbolOption($0) }
    }

    /// Returns all validated symbols across all categories
    static func allValidatedSymbols() -> [SFSymbolOption] {
        allSymbolNames.filter { symbolExists($0) }.map { SFSymbolOption($0) }
    }

    /// All category names
    static var categoryNames: [String] {
        Array(allCategories.keys).sorted()
    }

    /// Flat list of all symbol names
    static var allSymbolNames: [String] {
        allCategories.values.flatMap { $0 }
    }

    // MARK: - Symbol Categories

    static let allCategories: [String: [String]] = [
        "Communication": communicationSymbols,
        "Weather": weatherSymbols,
        "Objects & Tools": objectsSymbols,
        "Devices": devicesSymbols,
        "Gaming": gamingSymbols,
        "Connectivity": connectivitySymbols,
        "Transportation": transportationSymbols,
        "Human": humanSymbols,
        "Nature": natureSymbols,
        "Editing": editingSymbols,
        "Text Formatting": textFormattingSymbols,
        "Media": mediaSymbols,
        "Keyboard": keyboardSymbols,
        "Commerce": commerceSymbols,
        "Time": timeSymbols,
        "Health": healthSymbols,
        "Shapes": shapesSymbols,
        "Arrows": arrowsSymbols,
        "Math": mathSymbols,
        "Privacy & Security": privacySymbols,
        "Home": homeSymbols,
        "Fitness": fitnessSymbols,
        "Accessibility": accessibilitySymbols,
        "Indices": indicesSymbols,
    ]

    // MARK: - Communication
    static let communicationSymbols = [
        "mic", "mic.fill", "mic.slash", "mic.slash.fill", "mic.badge.plus",
        "mic.circle", "mic.circle.fill", "mic.square", "mic.square.fill",
        "message", "message.fill", "message.circle", "message.circle.fill",
        "message.badge", "message.badge.fill", "bubble.right", "bubble.right.fill",
        "bubble.left", "bubble.left.fill", "bubble.left.and.bubble.right",
        "bubble.left.and.bubble.right.fill", "bubble.middle.bottom", "bubble.middle.bottom.fill",
        "bubble.middle.top", "bubble.middle.top.fill", "exclamationmark.bubble",
        "exclamationmark.bubble.fill", "quote.bubble", "quote.bubble.fill",
        "star.bubble", "star.bubble.fill", "character.bubble", "character.bubble.fill",
        "text.bubble", "text.bubble.fill", "captions.bubble", "captions.bubble.fill",
        "plus.bubble", "plus.bubble.fill", "ellipsis.bubble", "ellipsis.bubble.fill",
        "phone", "phone.fill", "phone.circle", "phone.circle.fill",
        "phone.badge.plus", "phone.fill.badge.plus", "phone.connection",
        "phone.arrow.up.right", "phone.arrow.down.left", "phone.arrow.right",
        "phone.down", "phone.down.fill", "phone.down.circle", "phone.down.circle.fill",
        "envelope", "envelope.fill", "envelope.circle", "envelope.circle.fill",
        "envelope.open", "envelope.open.fill", "envelope.badge", "envelope.badge.fill",
        "envelope.badge.shield.half.filled", "mail", "mail.fill", "mail.stack", "mail.stack.fill",
        "paperplane", "paperplane.fill", "paperplane.circle", "paperplane.circle.fill",
        "tray", "tray.fill", "tray.circle", "tray.circle.fill",
        "tray.and.arrow.up", "tray.and.arrow.up.fill", "tray.and.arrow.down",
        "tray.and.arrow.down.fill", "tray.2", "tray.2.fill", "tray.full", "tray.full.fill",
        "megaphone", "megaphone.fill", "speaker", "speaker.fill",
        "speaker.wave.1", "speaker.wave.1.fill", "speaker.wave.2", "speaker.wave.2.fill",
        "speaker.wave.3", "speaker.wave.3.fill", "speaker.slash", "speaker.slash.fill",
        "speaker.zzz", "speaker.zzz.fill", "speaker.badge.exclamationmark",
        "speaker.badge.exclamationmark.fill", "video", "video.fill", "video.circle",
        "video.circle.fill", "video.slash", "video.slash.fill", "video.badge.plus",
        "video.fill.badge.plus", "video.badge.checkmark", "video.fill.badge.checkmark",
        "arrow.up.right.video", "arrow.up.right.video.fill", "arrow.down.left.video",
        "arrow.down.left.video.fill", "person.wave.2", "person.wave.2.fill",
    ]

    // MARK: - Weather
    static let weatherSymbols = [
        "sun.min", "sun.min.fill", "sun.max", "sun.max.fill",
        "sun.and.horizon", "sun.and.horizon.fill", "sun.dust", "sun.dust.fill",
        "sun.haze", "sun.haze.fill", "sunrise", "sunrise.fill",
        "sunset", "sunset.fill", "moon", "moon.fill",
        "moon.circle", "moon.circle.fill", "moon.stars", "moon.stars.fill",
        "moon.zzz", "moon.zzz.fill", "sparkle", "sparkles",
        "moon.haze", "moon.haze.fill", "cloud", "cloud.fill",
        "cloud.drizzle", "cloud.drizzle.fill", "cloud.rain", "cloud.rain.fill",
        "cloud.heavyrain", "cloud.heavyrain.fill", "cloud.fog", "cloud.fog.fill",
        "cloud.hail", "cloud.hail.fill", "cloud.snow", "cloud.snow.fill",
        "cloud.sleet", "cloud.sleet.fill", "cloud.bolt", "cloud.bolt.fill",
        "cloud.bolt.rain", "cloud.bolt.rain.fill", "cloud.sun", "cloud.sun.fill",
        "cloud.sun.rain", "cloud.sun.rain.fill", "cloud.sun.bolt", "cloud.sun.bolt.fill",
        "cloud.moon", "cloud.moon.fill", "cloud.moon.rain", "cloud.moon.rain.fill",
        "cloud.moon.bolt", "cloud.moon.bolt.fill", "smoke", "smoke.fill",
        "wind", "wind.snow", "snowflake", "snowflake.circle", "snowflake.circle.fill",
        "tornado", "tropicalstorm", "hurricane", "thermometer.sun", "thermometer.sun.fill",
        "thermometer.snowflake", "thermometer", "aqi.low", "aqi.medium", "aqi.high",
        "humidity", "humidity.fill", "rainbow", "umbrella", "umbrella.fill",
    ]

    // MARK: - Objects & Tools
    static let objectsSymbols = [
        "pencil", "pencil.circle", "pencil.circle.fill", "pencil.slash",
        "pencil.line", "pencil.and.outline", "pencil.tip", "pencil.tip.crop.circle",
        "pencil.tip.crop.circle.badge.plus", "pencil.tip.crop.circle.badge.minus",
        "pencil.tip.crop.circle.badge.arrow.forward", "lasso", "lasso.and.sparkles",
        "trash", "trash.fill", "trash.circle", "trash.circle.fill",
        "trash.slash", "trash.slash.fill", "folder", "folder.fill",
        "folder.circle", "folder.circle.fill", "folder.badge.plus", "folder.fill.badge.plus",
        "folder.badge.minus", "folder.fill.badge.minus", "folder.badge.questionmark",
        "folder.fill.badge.questionmark", "folder.badge.gearshape", "folder.fill.badge.gearshape",
        "paperclip", "paperclip.circle", "paperclip.circle.fill", "paperclip.badge.ellipsis",
        "rectangle.and.paperclip", "rectangle.dashed.and.paperclip",
        "link", "link.circle", "link.circle.fill", "link.badge.plus",
        "personalhotspot", "personalhotspot.circle", "personalhotspot.circle.fill",
        "scissors", "scissors.circle", "scissors.circle.fill", "scissors.badge.ellipsis",
        "doc", "doc.fill", "doc.circle", "doc.circle.fill",
        "doc.badge.plus", "doc.fill.badge.plus", "doc.badge.gearshape",
        "doc.badge.gearshape.fill", "doc.badge.ellipsis", "doc.text", "doc.text.fill",
        "doc.zipper", "doc.on.doc", "doc.on.doc.fill", "doc.on.clipboard",
        "doc.on.clipboard.fill", "clipboard", "clipboard.fill",
        "list.clipboard", "list.clipboard.fill", "doc.richtext", "doc.richtext.fill",
        "doc.plaintext", "doc.plaintext.fill", "doc.append", "doc.append.fill",
        "doc.text.image", "doc.text.image.fill", "note", "note.text",
        "note.text.badge.plus", "calendar", "calendar.circle", "calendar.circle.fill",
        "calendar.badge.plus", "calendar.badge.minus", "calendar.badge.clock",
        "calendar.badge.exclamationmark", "calendar.day.timeline.left",
        "calendar.day.timeline.right", "calendar.day.timeline.leading",
        "calendar.day.timeline.trailing", "arrowshape.turn.up.left",
        "arrowshape.turn.up.left.fill", "arrowshape.turn.up.left.circle",
        "arrowshape.turn.up.left.circle.fill", "arrowshape.turn.up.right",
        "arrowshape.turn.up.right.fill", "arrowshape.turn.up.right.circle",
        "arrowshape.turn.up.right.circle.fill", "arrowshape.turn.up.left.2",
        "arrowshape.turn.up.left.2.fill", "arrowshape.turn.up.left.2.circle",
        "arrowshape.turn.up.left.2.circle.fill", "book", "book.fill",
        "book.circle", "book.circle.fill", "book.closed", "book.closed.fill",
        "book.closed.circle", "book.closed.circle.fill", "character.book.closed",
        "character.book.closed.fill", "text.book.closed", "text.book.closed.fill",
        "books.vertical", "books.vertical.fill", "books.vertical.circle",
        "books.vertical.circle.fill", "bookshelf", "bookshelf.fill",
        "greetingcard", "greetingcard.fill", "magazine", "magazine.fill",
        "newspaper", "newspaper.fill", "newspaper.circle", "newspaper.circle.fill",
        "bookmark", "bookmark.fill", "bookmark.circle", "bookmark.circle.fill",
        "bookmark.square", "bookmark.square.fill", "bookmark.slash", "bookmark.slash.fill",
        "rosette", "graduationcap", "graduationcap.fill", "graduationcap.circle",
        "graduationcap.circle.fill", "ticket", "ticket.fill",
        "paperplane", "paperplane.fill", "paperplane.circle", "paperplane.circle.fill",
        "externaldrive", "externaldrive.fill", "externaldrive.badge.plus",
        "externaldrive.fill.badge.plus", "externaldrive.badge.minus",
        "externaldrive.fill.badge.minus", "externaldrive.badge.checkmark",
        "externaldrive.fill.badge.checkmark", "externaldrive.badge.xmark",
        "externaldrive.fill.badge.xmark", "externaldrive.badge.questionmark",
        "externaldrive.fill.badge.questionmark", "externaldrive.badge.wifi",
        "externaldrive.fill.badge.wifi", "internaldrive", "internaldrive.fill",
        "opticaldiscdrive", "opticaldiscdrive.fill", "archivebox",
        "archivebox.fill", "archivebox.circle", "archivebox.circle.fill",
        "xmark.bin", "xmark.bin.fill", "xmark.bin.circle", "xmark.bin.circle.fill",
        "arrow.up.bin", "arrow.up.bin.fill", "doc.badge.arrow.up", "doc.badge.arrow.up.fill",
        "tag", "tag.fill", "tag.circle", "tag.circle.fill",
        "tag.square", "tag.square.fill", "tag.slash", "tag.slash.fill",
        "gearshape", "gearshape.fill", "gearshape.circle", "gearshape.circle.fill",
        "gearshape.2", "gearshape.2.fill", "gear", "gear.circle", "gear.circle.fill",
        "signature", "line.diagonal", "line.diagonal.arrow",
        "hammer", "hammer.fill", "hammer.circle", "hammer.circle.fill",
        "screwdriver", "screwdriver.fill", "wrench", "wrench.fill",
        "wrench.adjustable", "wrench.adjustable.fill", "wrench.and.screwdriver",
        "wrench.and.screwdriver.fill", "scroll", "scroll.fill",
        "stethoscope", "stethoscope.circle", "stethoscope.circle.fill",
        "printer", "printer.fill", "printer.filled.and.paper", "printer.dotmatrix",
        "printer.dotmatrix.fill", "printer.dotmatrix.filled.and.paper",
        "scanner", "scanner.fill", "faxmachine", "faxmachine.fill",
        "briefcase", "briefcase.fill", "briefcase.circle", "briefcase.circle.fill",
        "case", "case.fill", "latch.2.case", "latch.2.case.fill",
        "cross.case", "cross.case.fill", "cross.case.circle", "cross.case.circle.fill",
        "suitcase", "suitcase.fill", "suitcase.cart", "suitcase.cart.fill",
        "theatermasks", "theatermasks.fill", "theatermasks.circle", "theatermasks.circle.fill",
        "puzzlepiece", "puzzlepiece.fill", "puzzlepiece.extension", "puzzlepiece.extension.fill",
        "house", "house.fill", "house.circle", "house.circle.fill",
        "building", "building.fill", "building.2", "building.2.fill",
        "building.2.crop.circle", "building.2.crop.circle.fill",
        "lightbulb", "lightbulb.fill", "lightbulb.circle", "lightbulb.circle.fill",
        "lightbulb.slash", "lightbulb.slash.fill", "lightbulb.led", "lightbulb.led.fill",
        "lightbulb.led.wide", "lightbulb.led.wide.fill", "lightbulb.min", "lightbulb.min.fill",
        "lightbulb.max", "lightbulb.max.fill", "fanblades", "fanblades.fill",
        "lamp.desk", "lamp.desk.fill", "lamp.table", "lamp.table.fill",
        "lamp.floor", "lamp.floor.fill", "lamp.ceiling", "lamp.ceiling.fill",
        "lamp.ceiling.inverse", "chandelier", "chandelier.fill",
        "fan", "fan.fill", "fan.ceiling", "fan.ceiling.fill",
        "fan.desk", "fan.desk.fill", "fan.floor", "fan.floor.fill",
        "gift", "gift.fill", "gift.circle", "gift.circle.fill",
        "party.popper", "party.popper.fill", "balloon", "balloon.fill",
        "balloon.2", "balloon.2.fill", "hourglass", "hourglass.circle",
        "hourglass.circle.fill", "hourglass.bottomhalf.filled", "hourglass.tophalf.filled",
        "battery.100", "battery.75", "battery.50", "battery.25",
        "battery.0", "battery.100.bolt", "bolt.fill", "bolt.circle",
        "bolt.circle.fill", "bolt.square", "bolt.square.fill", "bolt.shield",
        "bolt.shield.fill", "bolt.slash", "bolt.slash.fill", "bolt.slash.circle",
        "bolt.slash.circle.fill", "bolt.badge.a", "bolt.badge.a.fill",
        "bolt.badge.automatic", "bolt.badge.automatic.fill",
        "lock", "lock.fill", "lock.circle", "lock.circle.fill",
        "lock.square", "lock.square.fill", "lock.square.stack", "lock.square.stack.fill",
        "lock.rectangle", "lock.rectangle.fill", "lock.rectangle.stack",
        "lock.rectangle.stack.fill", "lock.rectangle.on.rectangle",
        "lock.rectangle.on.rectangle.fill", "lock.shield", "lock.shield.fill",
        "lock.slash", "lock.slash.fill", "lock.open", "lock.open.fill",
        "lock.open.trianglebadge.exclamationmark", "lock.open.trianglebadge.exclamationmark.fill",
        "key", "key.fill", "key.radiowaves.forward", "key.radiowaves.forward.fill",
        "key.horizontal", "key.horizontal.fill", "key.viewfinder", "lock.badge.clock",
        "lock.badge.clock.fill", "pin", "pin.fill", "pin.circle", "pin.circle.fill",
        "pin.square", "pin.square.fill", "pin.slash", "pin.slash.fill",
        "map", "map.fill", "map.circle", "map.circle.fill",
        "mappin", "mappin.circle", "mappin.circle.fill", "mappin.square",
        "mappin.square.fill", "mappin.slash", "mappin.slash.circle",
        "mappin.slash.circle.fill", "mappin.and.ellipse", "location", "location.fill",
        "location.circle", "location.circle.fill", "location.square", "location.square.fill",
        "location.slash", "location.slash.fill", "location.north", "location.north.fill",
        "location.north.circle", "location.north.circle.fill",
        "location.north.line", "location.north.line.fill",
        "flag", "flag.fill", "flag.circle", "flag.circle.fill",
        "flag.square", "flag.square.fill", "flag.slash", "flag.slash.fill",
        "flag.slash.circle", "flag.slash.circle.fill", "flag.badge.ellipsis",
        "flag.badge.ellipsis.fill", "flag.2.crossed", "flag.2.crossed.fill",
        "flag.2.crossed.circle", "flag.2.crossed.circle.fill",
        "bell", "bell.fill", "bell.circle", "bell.circle.fill",
        "bell.square", "bell.square.fill", "bell.slash", "bell.slash.fill",
        "bell.slash.circle", "bell.slash.circle.fill", "bell.badge", "bell.badge.fill",
        "bell.badge.circle", "bell.badge.circle.fill", "bell.and.waves.left.and.right",
        "bell.and.waves.left.and.right.fill",
    ]

    // MARK: - Devices
    static let devicesSymbols = [
        "keyboard", "keyboard.fill", "keyboard.badge.ellipsis", "keyboard.badge.ellipsis.fill",
        "keyboard.badge.eye", "keyboard.badge.eye.fill", "keyboard.chevron.compact.down",
        "keyboard.chevron.compact.down.fill", "keyboard.chevron.compact.left",
        "keyboard.chevron.compact.left.fill", "keyboard.onehanded.left",
        "keyboard.onehanded.left.fill", "keyboard.onehanded.right", "keyboard.onehanded.right.fill",
        "rectangle.and.hand.point.up.left", "rectangle.and.hand.point.up.left.fill",
        "rectangle.and.hand.point.up.left.filled",
        "iphone", "iphone.circle", "iphone.circle.fill", "iphone.slash", "iphone.slash.circle",
        "iphone.homebutton", "iphone.homebutton.circle", "iphone.homebutton.circle.fill",
        "iphone.homebutton.slash", "iphone.homebutton.slash.circle",
        "iphone.badge.play", "iphone.homebutton.badge.play",
        "iphone.gen1", "iphone.gen1.circle", "iphone.gen1.circle.fill",
        "iphone.gen1.slash", "iphone.gen1.slash.circle",
        "iphone.gen2", "iphone.gen2.circle", "iphone.gen2.circle.fill",
        "iphone.gen3", "iphone.gen3.circle", "iphone.gen3.circle.fill",
        "iphone.gen3.slash", "iphone.gen3.slash.circle",
        "ipad", "ipad.landscape", "ipad.homebutton", "ipad.homebutton.landscape",
        "ipad.gen1", "ipad.gen1.landscape", "ipad.gen2", "ipad.gen2.landscape",
        "ipad.badge.play", "ipad.homebutton.badge.play",
        "ipod", "ipodshuffle.gen1", "ipodshuffle.gen2", "ipodshuffle.gen3", "ipodshuffle.gen4",
        "ipodtouch", "ipodtouch.slash", "ipodtouch.landscape",
        "laptopcomputer", "laptopcomputer.slash", "laptopcomputer.trianglebadge.exclamationmark",
        "macbook", "macbook.gen1", "macbook.gen2",
        "pc", "macpro.gen1", "macpro.gen1.fill", "macpro.gen2", "macpro.gen2.fill",
        "macpro.gen3", "macpro.gen3.fill", "macpro.gen3.server",
        "server.rack", "xserve", "xserve.raid",
        "desktopcomputer", "macmini", "macmini.fill", "macstudio", "macstudio.fill",
        "display", "display.2", "display.trianglebadge.exclamationmark",
        "monitor", "laptopcomputer.and.iphone", "laptopcomputer.and.ipad",
        "applewatch", "applewatch.watchface", "applewatch.radiowaves.left.and.right",
        "applewatch.slash", "applewatch.side.right", "applewatch.case.inset.filled",
        "airpods", "airpod.right", "airpod.left", "airpods.chargingcase",
        "airpods.chargingcase.fill", "airpods.chargingcase.wireless",
        "airpods.chargingcase.wireless.fill", "airpodspro", "airpodspro.chargingcase.wireless",
        "airpodspro.chargingcase.wireless.fill", "airpodsmax",
        "earpods", "beats.headphones", "beats.earphones", "beats.powerbeatspro",
        "beats.powerbeatspro.right", "beats.powerbeatspro.left", "beats.powerbeats",
        "beats.powerbeats3", "beats.studiobud", "beats.studiobud.left", "beats.studiobud.right",
        "beats.studiobuds.chargingcase", "beats.studiobuds.chargingcase.fill",
        "beats.fit.pro", "beats.fit.pro.left", "beats.fit.pro.right",
        "beats.fit.pro.chargingcase", "beats.fit.pro.chargingcase.fill",
        "homepod", "homepod.fill", "homepod.2", "homepod.2.fill",
        "homepodmini", "homepodmini.fill", "homepodmini.2", "homepodmini.2.fill",
        "hifispeaker", "hifispeaker.fill", "hifispeaker.2", "hifispeaker.2.fill",
        "appletv", "appletv.fill", "appletvremote.gen1", "appletvremote.gen1.fill",
        "appletvremote.gen2", "appletvremote.gen2.fill", "appletvremote.gen3",
        "appletvremote.gen3.fill", "appletvremote.gen4", "appletvremote.gen4.fill",
        "mediastick", "cable.connector", "cable.connector.horizontal",
        "tv", "tv.fill", "tv.inset.filled", "tv.circle", "tv.circle.fill",
        "tv.slash", "tv.slash.fill", "tv.badge.wifi", "tv.badge.wifi.fill",
        "opticaldisc", "opticaldisc.fill", "memorychip", "memorychip.fill",
        "cpu", "cpu.fill", "headphones", "headphones.circle", "headphones.circle.fill",
        "gamecontroller", "gamecontroller.fill", "logo.playstation", "logo.xbox",
        "power", "power.circle", "power.circle.fill", "power.dotted",
        "togglepower", "poweron", "poweroff", "powersleep",
        "wake", "sleep", "sleep.circle", "sleep.circle.fill",
        "wifi", "wifi.circle", "wifi.circle.fill", "wifi.square", "wifi.square.fill",
        "wifi.slash", "wifi.exclamationmark", "wifi.router", "wifi.router.fill",
        "antenna.radiowaves.left.and.right", "antenna.radiowaves.left.and.right.circle",
        "antenna.radiowaves.left.and.right.circle.fill", "antenna.radiowaves.left.and.right.slash",
    ]

    // MARK: - Gaming
    static let gamingSymbols = [
        "gamecontroller", "gamecontroller.fill",
        "dpad", "dpad.fill", "dpad.up.filled", "dpad.down.filled",
        "dpad.left.filled", "dpad.right.filled",
        "circle.grid.cross", "circle.grid.cross.fill",
        "circle.grid.cross.up.filled", "circle.grid.cross.down.filled",
        "circle.grid.cross.left.filled", "circle.grid.cross.right.filled",
        "l.joystick", "r.joystick", "l.joystick.fill", "r.joystick.fill",
        "l.joystick.press.down", "l.joystick.press.down.fill",
        "r.joystick.press.down", "r.joystick.press.down.fill",
        "l.joystick.tilt.left", "l.joystick.tilt.left.fill",
        "l.joystick.tilt.right", "l.joystick.tilt.right.fill",
        "l.joystick.tilt.up", "l.joystick.tilt.up.fill",
        "l.joystick.tilt.down", "l.joystick.tilt.down.fill",
        "r.joystick.tilt.left", "r.joystick.tilt.left.fill",
        "r.joystick.tilt.right", "r.joystick.tilt.right.fill",
        "r.joystick.tilt.up", "r.joystick.tilt.up.fill",
        "r.joystick.tilt.down", "r.joystick.tilt.down.fill",
        "l1.rectangle.roundedbottom", "l1.rectangle.roundedbottom.fill",
        "l2.rectangle.roundedtop", "l2.rectangle.roundedtop.fill",
        "r1.rectangle.roundedbottom", "r1.rectangle.roundedbottom.fill",
        "r2.rectangle.roundedtop", "r2.rectangle.roundedtop.fill",
        "lb.rectangle.roundedbottom", "lb.rectangle.roundedbottom.fill",
        "rb.rectangle.roundedbottom", "rb.rectangle.roundedbottom.fill",
        "lt.rectangle.roundedtop", "lt.rectangle.roundedtop.fill",
        "rt.rectangle.roundedtop", "rt.rectangle.roundedtop.fill",
        "zl.rectangle.roundedtop", "zl.rectangle.roundedtop.fill",
        "zr.rectangle.roundedtop", "zr.rectangle.roundedtop.fill",
        "xbox.logo", "playstation.logo",
    ]

    // MARK: - Connectivity
    static let connectivitySymbols = [
        "wifi", "wifi.circle", "wifi.circle.fill", "wifi.square", "wifi.square.fill",
        "wifi.slash", "wifi.exclamationmark", "wifi.router", "wifi.router.fill",
        "dot.radiowaves.left.and.right", "dot.radiowaves.right", "dot.radiowaves.forward",
        "wave.3.left", "wave.3.left.circle", "wave.3.left.circle.fill",
        "wave.3.right", "wave.3.right.circle", "wave.3.right.circle.fill",
        "wave.3.forward", "wave.3.forward.circle", "wave.3.forward.circle.fill",
        "wave.3.backward", "wave.3.backward.circle", "wave.3.backward.circle.fill",
        "antenna.radiowaves.left.and.right",
        "antenna.radiowaves.left.and.right.circle",
        "antenna.radiowaves.left.and.right.circle.fill",
        "antenna.radiowaves.left.and.right.slash",
        "airtag", "airtag.fill", "airtag.radiowaves.forward",
        "airtag.radiowaves.forward.fill", "airtag.radiowaves.forward.fill.badge.exclamationmark",
        "personalhotspot", "personalhotspot.circle", "personalhotspot.circle.fill",
        "network", "network.badge.shield.half.filled", "network.slash",
        "bolt.horizontal", "bolt.horizontal.fill", "bolt.horizontal.circle",
        "bolt.horizontal.circle.fill", "globe", "globe.americas", "globe.americas.fill",
        "globe.europe.africa", "globe.europe.africa.fill", "globe.asia.australia",
        "globe.asia.australia.fill", "globe.central.south.asia", "globe.central.south.asia.fill",
        "globe.badge.chevron.backward", "shareplay", "shareplay.slash",
    ]

    // MARK: - Transportation
    static let transportationSymbols = [
        "car", "car.fill", "car.circle", "car.circle.fill",
        "bolt.car", "bolt.car.fill", "bolt.car.circle", "bolt.car.circle.fill",
        "car.2", "car.2.fill", "bus", "bus.fill", "bus.doubledecker",
        "bus.doubledecker.fill", "tram", "tram.fill", "tram.circle", "tram.circle.fill",
        "tram.tunnel.fill", "cablecar", "cablecar.fill", "ferry", "ferry.fill",
        "car.ferry", "car.ferry.fill", "train.side.front.car", "train.side.middle.car",
        "train.side.rear.car", "box.truck", "box.truck.fill", "box.truck.badge.clock",
        "box.truck.badge.clock.fill", "bicycle", "bicycle.circle", "bicycle.circle.fill",
        "scooter", "fuelpump", "fuelpump.fill", "fuelpump.circle", "fuelpump.circle.fill",
        "ev.charger", "ev.charger.fill", "ev.charger.slash", "ev.charger.slash.fill",
        "ev.charger.arrowtriangle.left", "ev.charger.arrowtriangle.left.fill",
        "ev.charger.arrowtriangle.right", "ev.charger.arrowtriangle.right.fill",
        "ev.charger.exclamationmark", "ev.charger.exclamationmark.fill",
        "steeringwheel", "steeringwheel.exclamationmark", "steeringwheel.badge.exclamationmark",
        "steeringwheel.road.lane", "steeringwheel.road.lane.dashed",
        "steeringwheel.and.heat.waves", "steeringwheel.and.liquid.wave",
        "parkinglight", "parkinglight.fill", "headlight.high.beam", "headlight.high.beam.fill",
        "headlight.low.beam", "headlight.low.beam.fill", "road.lanes", "road.lanes.curved.right",
        "road.lanes.curved.left", "airplane", "airplane.circle", "airplane.circle.fill",
        "airplane.departure", "airplane.arrival",
    ]

    // MARK: - Human
    static let humanSymbols = [
        "person", "person.fill", "person.circle", "person.circle.fill",
        "person.slash", "person.slash.fill", "person.fill.badge.plus",
        "person.fill.badge.minus", "person.fill.xmark", "person.fill.checkmark",
        "person.fill.questionmark", "person.badge.plus", "person.badge.minus",
        "person.badge.clock", "person.badge.clock.fill", "person.badge.key",
        "person.badge.key.fill", "person.badge.shield.checkmark",
        "person.badge.shield.checkmark.fill", "person.2", "person.2.fill",
        "person.2.circle", "person.2.circle.fill", "person.2.slash", "person.2.slash.fill",
        "person.3", "person.3.fill", "person.3.sequence", "person.3.sequence.fill",
        "person.crop.circle", "person.crop.circle.fill", "person.crop.circle.badge",
        "person.crop.circle.badge.plus", "person.crop.circle.badge.minus",
        "person.crop.circle.badge.checkmark", "person.crop.circle.badge.xmark",
        "person.crop.circle.badge.questionmark", "person.crop.circle.badge.exclamationmark",
        "person.crop.circle.badge.moon", "person.crop.circle.badge.clock",
        "person.crop.circle.dashed", "person.crop.circle.dashed.fill",
        "person.crop.square", "person.crop.square.fill", "person.crop.artframe",
        "person.crop.rectangle", "person.crop.rectangle.fill", "person.crop.rectangle.stack",
        "person.crop.rectangle.stack.fill", "person.text.rectangle",
        "person.text.rectangle.fill", "person.viewfinder", "shared.with.you",
        "shared.with.you.slash", "rectangle.inset.filled.and.person.filled",
        "person.and.arrow.left.and.arrow.right", "person.fill.and.arrow.left.and.arrow.right",
        "person.2.gobackward", "figure.stand", "figure.stand.line.dotted.figure.stand",
        "figure.walk", "figure.walk.circle", "figure.walk.circle.fill",
        "figure.walk.diamond", "figure.walk.diamond.fill", "figure.walk.arrival",
        "figure.walk.departure", "figure.walk.motion", "figure.run", "figure.run.circle",
        "figure.run.circle.fill", "figure.dance", "figure.roll", "figure.roll.runningpace",
        "figure.american.football", "figure.archery", "figure.australian.football",
        "figure.badminton", "figure.barre", "figure.baseball", "figure.basketball",
        "figure.bowling", "figure.boxing", "figure.climbing", "figure.cooldown",
        "figure.core.training", "figure.cricket", "figure.cross.training", "figure.curling",
        "figure.disc.sports", "figure.elliptical", "figure.equestrian.sports",
        "figure.fencing", "figure.fishing", "figure.flexibility", "figure.golf",
        "figure.gymnastics", "figure.hand.cycling", "figure.handball", "figure.highintensity.intervaltraining",
        "figure.hiking", "figure.hockey", "figure.hunting", "figure.indoor.cycle",
        "figure.jumprope", "figure.kickboxing", "figure.lacrosse", "figure.martial.arts",
        "figure.mind.and.body", "figure.mixed.cardio", "figure.open.water.swim",
        "figure.outdoor.cycle", "figure.pickleball", "figure.pilates", "figure.play",
        "figure.pool.swim", "figure.racquetball", "figure.rolling", "figure.rower",
        "figure.rugby", "figure.sailing", "figure.skating", "figure.skiing.crosscountry",
        "figure.skiing.downhill", "figure.snowboarding", "figure.soccer",
        "figure.socialdance", "figure.softball", "figure.squash", "figure.stair.stepper",
        "figure.stairs", "figure.step.training", "figure.surfing", "figure.table.tennis",
        "figure.taichi", "figure.tennis", "figure.track.and.field", "figure.volleyball",
        "figure.water.fitness", "figure.waterpolo", "figure.wave", "figure.wrestling",
        "figure.yoga", "hand.raised", "hand.raised.fill", "hand.raised.circle",
        "hand.raised.circle.fill", "hand.raised.square", "hand.raised.square.fill",
        "hand.raised.slash", "hand.raised.slash.fill", "hand.thumbsup", "hand.thumbsup.fill",
        "hand.thumbsup.circle", "hand.thumbsup.circle.fill", "hand.thumbsdown",
        "hand.thumbsdown.fill", "hand.thumbsdown.circle", "hand.thumbsdown.circle.fill",
        "hand.point.up.left", "hand.point.up.left.fill", "hand.point.up.braille",
        "hand.point.up.braille.fill", "hand.draw", "hand.draw.fill", "hand.tap",
        "hand.tap.fill", "hand.wave", "hand.wave.fill", "hands.clap", "hands.clap.fill",
        "hands.sparkles", "hands.sparkles.fill", "ear", "ear.badge.checkmark",
        "ear.trianglebadge.exclamationmark", "ear.and.waveform", "ear.fill",
        "eye", "eye.fill", "eye.circle", "eye.circle.fill", "eye.square", "eye.square.fill",
        "eye.slash", "eye.slash.fill", "eye.slash.circle", "eye.slash.circle.fill",
        "eye.trianglebadge.exclamationmark", "eye.trianglebadge.exclamationmark.fill",
        "eyes", "eyes.inverse", "mustache", "mustache.fill", "nose", "nose.fill",
        "mouth", "mouth.fill", "brain", "brain.head.profile",
    ]

    // MARK: - Nature
    static let natureSymbols = [
        "flame", "flame.fill", "flame.circle", "flame.circle.fill",
        "drop", "drop.fill", "drop.circle", "drop.circle.fill",
        "drop.triangle", "drop.triangle.fill", "drop.degreesign", "drop.degreesign.fill",
        "drop.degreesign.slash", "drop.degreesign.slash.fill",
        "leaf", "leaf.fill", "leaf.circle", "leaf.circle.fill",
        "leaf.arrow.triangle.circlepath", "tree", "tree.fill", "tree.circle",
        "tree.circle.fill", "fish", "fish.fill", "fish.circle", "fish.circle.fill",
        "hare", "hare.fill", "tortoise", "tortoise.fill", "ant", "ant.fill",
        "ant.circle", "ant.circle.fill", "ladybug", "ladybug.fill",
        "bird", "bird.fill", "bird.circle", "bird.circle.fill",
        "dog", "dog.fill", "dog.circle", "dog.circle.fill",
        "cat", "cat.fill", "cat.circle", "cat.circle.fill",
        "lizard", "lizard.fill", "lizard.circle", "lizard.circle.fill",
        "pawprint", "pawprint.fill", "pawprint.circle", "pawprint.circle.fill",
        "teddybear", "teddybear.fill", "fossil.shell", "fossil.shell.fill",
        "mountain.2", "mountain.2.fill", "mountain.2.circle", "mountain.2.circle.fill",
        "globe", "globe.americas", "globe.americas.fill", "globe.europe.africa",
        "globe.europe.africa.fill", "globe.asia.australia", "globe.asia.australia.fill",
        "globe.central.south.asia", "globe.central.south.asia.fill",
    ]

    // MARK: - Editing
    static let editingSymbols = [
        "pencil", "pencil.circle", "pencil.circle.fill", "pencil.slash",
        "pencil.line", "pencil.and.outline", "pencil.tip", "pencil.tip.crop.circle",
        "pencil.tip.crop.circle.badge.plus", "pencil.tip.crop.circle.badge.minus",
        "pencil.tip.crop.circle.badge.arrow.forward", "lasso", "lasso.and.sparkles",
        "highlighter", "eraser", "eraser.fill", "eraser.line.dashed",
        "eraser.line.dashed.fill", "scribble", "scribble.variable",
        "paintbrush", "paintbrush.fill", "paintbrush.pointed", "paintbrush.pointed.fill",
        "bandage", "bandage.fill", "ruler", "ruler.fill",
        "slider.horizontal.3", "slider.horizontal.below.rectangle",
        "slider.horizontal.below.square.filled.and.square", "slider.vertical.3",
        "crop", "crop.rotate", "dial.low", "dial.low.fill",
        "dial.medium", "dial.medium.fill", "dial.high", "dial.high.fill",
        "gyroscope", "loupe", "wand.and.rays", "wand.and.rays.inverse",
        "wand.and.stars", "wand.and.stars.inverse", "eyedropper",
        "eyedropper.halffull", "eyedropper.full", "rotate.left", "rotate.left.fill",
        "rotate.right", "rotate.right.fill", "selection.pin.in.out",
        "move.3d", "scale.3d", "rotate.3d", "rotate.3d.fill",
    ]

    // MARK: - Text Formatting
    static let textFormattingSymbols = [
        "textformat", "textformat.alt", "textformat.size", "textformat.size.smaller",
        "textformat.size.larger", "textformat.superscript", "textformat.subscript",
        "abc", "textformat.abc", "textformat.abc.dottedunderline",
        "bold", "italic", "underline", "strikethrough",
        "bold.italic.underline", "bold.underline", "a.magnify",
        "text.alignleft", "text.aligncenter", "text.alignright", "text.justify",
        "text.justify.left", "text.justify.right", "text.justify.leading",
        "text.justify.trailing", "text.redaction", "list.bullet", "list.bullet.circle",
        "list.bullet.circle.fill", "list.dash", "list.dash.header.rectangle",
        "list.bullet.indent", "list.number", "list.star", "list.triangle",
        "increase.indent", "decrease.indent", "increase.quotelevel", "decrease.quotelevel",
        "text.quote", "text.insert", "text.append", "text.badge.plus",
        "text.badge.minus", "text.badge.checkmark", "text.badge.xmark",
        "text.badge.star", "paragraphsign", "text.word.spacing", "textformat.size.smaller.ja",
        "textformat.size.larger.ja", "textformat.size.smaller.zh",
        "textformat.size.larger.zh", "textformat.size.smaller.ko",
        "textformat.size.larger.ko", "textformat.size.smaller.th",
        "textformat.size.larger.th", "textformat.size.smaller.ar",
        "textformat.size.larger.ar", "textformat.size.smaller.he",
        "textformat.size.larger.he", "textformat.size.smaller.hi",
        "textformat.size.larger.hi", "character", "character.cursor.ibeam",
        "character.textbox", "a.square", "a.square.fill", "a.circle",
        "a.circle.fill", "abc.checkmark", "abc.arrow.right", "123.rectangle",
        "123.rectangle.fill", "character.book.closed", "character.book.closed.fill",
        "text.magnifyingglass", "text.cursor", "text.and.command.macwindow",
        "textformat.123", "textformat.12", "chevron.left.forwardslash.chevron.right",
        "parentheses", "curlybraces", "curlybraces.square", "curlybraces.square.fill",
    ]

    // MARK: - Media
    static let mediaSymbols = [
        "play", "play.fill", "play.circle", "play.circle.fill",
        "play.square", "play.square.fill", "play.rectangle", "play.rectangle.fill",
        "play.slash", "play.slash.fill", "pause", "pause.fill",
        "pause.circle", "pause.circle.fill", "pause.rectangle", "pause.rectangle.fill",
        "stop", "stop.fill", "stop.circle", "stop.circle.fill",
        "record.circle", "record.circle.fill", "playpause", "playpause.fill",
        "backward", "backward.fill", "forward", "forward.fill",
        "backward.end", "backward.end.fill", "forward.end", "forward.end.fill",
        "backward.frame", "backward.frame.fill", "forward.frame", "forward.frame.fill",
        "shuffle", "shuffle.circle", "shuffle.circle.fill",
        "repeat", "repeat.circle", "repeat.circle.fill", "repeat.1",
        "repeat.1.circle", "repeat.1.circle.fill", "infinity", "infinity.circle",
        "infinity.circle.fill", "megaphone", "megaphone.fill",
        "speaker", "speaker.fill", "speaker.slash", "speaker.slash.fill",
        "speaker.wave.1", "speaker.wave.1.fill", "speaker.wave.2", "speaker.wave.2.fill",
        "speaker.wave.3", "speaker.wave.3.fill", "speaker.zzz", "speaker.zzz.fill",
        "speaker.badge.exclamationmark", "speaker.badge.exclamationmark.fill",
        "music.note", "music.note.list", "music.quarternote.3",
        "music.mic", "music.mic.circle", "music.mic.circle.fill",
        "guitars", "guitars.fill", "piano.keys", "piano.keys.inverse",
        "tuningfork", "music.note.tv", "music.note.tv.fill",
        "photo", "photo.fill", "photo.circle", "photo.circle.fill",
        "photo.stack", "photo.stack.fill", "photo.on.rectangle", "photo.on.rectangle.angled",
        "photo.badge.plus", "photo.fill.badge.plus", "photo.badge.checkmark",
        "photo.fill.badge.checkmark", "photo.badge.arrow.down", "photo.fill.badge.arrow.down",
        "rectangle.on.rectangle", "rectangle.fill.on.rectangle.fill",
        "rectangle.on.rectangle.angled", "rectangle.fill.on.rectangle.angled.fill",
        "rectangle.on.rectangle.circle", "rectangle.on.rectangle.circle.fill",
        "rectangle.on.rectangle.square", "rectangle.on.rectangle.square.fill",
        "rectangle.on.rectangle.slash", "rectangle.on.rectangle.slash.fill",
        "rectangle.on.rectangle.slash.circle", "rectangle.on.rectangle.slash.circle.fill",
        "sparkles.rectangle.stack", "sparkles.rectangle.stack.fill",
        "camera", "camera.fill", "camera.circle", "camera.circle.fill",
        "camera.shutter.button", "camera.shutter.button.fill",
        "camera.badge.ellipsis", "camera.fill.badge.ellipsis",
        "arrow.triangle.2.circlepath.camera", "arrow.triangle.2.circlepath.camera.fill",
        "camera.on.rectangle", "camera.on.rectangle.fill",
        "camera.aperture", "camera.filters", "camera.macro", "camera.macro.circle",
        "camera.macro.circle.fill", "camera.viewfinder", "video", "video.fill",
        "video.circle", "video.circle.fill", "video.square", "video.square.fill",
        "video.slash", "video.slash.fill", "video.badge.plus", "video.fill.badge.plus",
        "video.badge.checkmark", "video.fill.badge.checkmark",
        "arrow.up.right.video", "arrow.up.right.video.fill",
        "arrow.down.left.video", "arrow.down.left.video.fill",
        "questionmark.video", "questionmark.video.fill",
        "film", "film.fill", "film.circle", "film.circle.fill",
        "film.stack", "film.stack.fill", "square.stack.3d.up",
        "square.stack.3d.up.fill", "square.stack.3d.up.slash",
        "square.stack.3d.up.slash.fill", "square.stack.3d.forward.dottedline",
        "square.stack.3d.forward.dottedline.fill",
    ]

    // MARK: - Keyboard
    static let keyboardSymbols = [
        "command", "command.circle", "command.circle.fill", "command.square",
        "command.square.fill", "option", "alt", "delete.left",
        "delete.left.fill", "delete.right", "delete.right.fill", "clear",
        "clear.fill", "deleteforward", "deleteforward.fill", "eject", "eject.fill",
        "eject.circle", "eject.circle.fill", "control", "controlkeys", "controlkeys.fill",
        "projective", "escape", "capslock", "capslock.fill",
        "shift", "shift.fill", "globe", "globe.americas", "globe.americas.fill",
        "network", "fn", "return", "return.left", "return.right",
        "power", "power.circle", "power.circle.fill", "power.dotted",
    ]

    // MARK: - Commerce
    static let commerceSymbols = [
        "cart", "cart.fill", "cart.circle", "cart.circle.fill",
        "cart.badge.plus", "cart.fill.badge.plus", "cart.badge.minus",
        "cart.fill.badge.minus", "cart.badge.questionmark", "cart.fill.badge.questionmark",
        "bag", "bag.fill", "bag.circle", "bag.circle.fill",
        "bag.badge.plus", "bag.fill.badge.plus", "bag.badge.minus", "bag.fill.badge.minus",
        "bag.badge.questionmark", "bag.fill.badge.questionmark",
        "creditcard", "creditcard.fill", "creditcard.circle", "creditcard.circle.fill",
        "creditcard.and.123", "creditcard.trianglebadge.exclamationmark",
        "giftcard", "giftcard.fill", "wallet.pass", "wallet.pass.fill",
        "dollarsign", "dollarsign.circle", "dollarsign.circle.fill",
        "dollarsign.square", "dollarsign.square.fill", "dollarsign.arrow.circlepath",
        "eurosign", "eurosign.circle", "eurosign.circle.fill",
        "eurosign.square", "eurosign.square.fill", "eurosign.arrow.circlepath",
        "yensign", "yensign.circle", "yensign.circle.fill",
        "yensign.square", "yensign.square.fill", "yensign.arrow.circlepath",
        "sterlingsign", "sterlingsign.circle", "sterlingsign.circle.fill",
        "sterlingsign.square", "sterlingsign.square.fill", "sterlingsign.arrow.circlepath",
        "francsign", "francsign.circle", "francsign.circle.fill",
        "francsign.square", "francsign.square.fill", "francsign.arrow.circlepath",
        "bitcoinsign", "bitcoinsign.circle", "bitcoinsign.circle.fill",
        "bitcoinsign.square", "bitcoinsign.square.fill",
        "barcode", "barcode.viewfinder", "qrcode", "qrcode.viewfinder",
        "percent", "purchased", "purchased.circle", "purchased.circle.fill",
        "storefront", "storefront.fill", "storefront.circle", "storefront.circle.fill",
        "building.columns", "building.columns.fill", "building.columns.circle",
        "building.columns.circle.fill", "banknote", "banknote.fill",
    ]

    // MARK: - Time
    static let timeSymbols = [
        "clock", "clock.fill", "clock.circle", "clock.circle.fill",
        "clock.badge", "clock.badge.fill", "clock.badge.checkmark",
        "clock.badge.checkmark.fill", "clock.badge.exclamationmark",
        "clock.badge.exclamationmark.fill", "clock.badge.questionmark",
        "clock.badge.questionmark.fill", "clock.badge.xmark", "clock.badge.xmark.fill",
        "clock.arrow.circlepath", "clock.arrow.2.circlepath",
        "alarm", "alarm.fill", "alarm.waves.left.and.right",
        "alarm.waves.left.and.right.fill", "stopwatch", "stopwatch.fill",
        "timer", "timer.circle", "timer.circle.fill", "timer.square",
        "chart.xyaxis.line", "gauge", "gauge.with.dots.needle.bottom.50percent",
        "gauge.with.dots.needle.bottom.0percent", "gauge.with.dots.needle.bottom.100percent",
        "gauge.with.dots.needle.33percent", "gauge.with.dots.needle.67percent",
        "gauge.with.needle", "gauge.with.needle.fill",
        "gauge.low", "gauge.medium", "gauge.high",
        "metronome", "metronome.fill", "speedometer",
        "calendar", "calendar.circle", "calendar.circle.fill",
        "calendar.badge.plus", "calendar.badge.minus", "calendar.badge.clock",
        "calendar.badge.exclamationmark", "calendar.badge.checkmark",
        "calendar.day.timeline.left", "calendar.day.timeline.right",
        "calendar.day.timeline.leading", "calendar.day.timeline.trailing",
    ]

    // MARK: - Health
    static let healthSymbols = [
        "heart", "heart.fill", "heart.circle", "heart.circle.fill",
        "heart.square", "heart.square.fill", "heart.slash", "heart.slash.fill",
        "heart.slash.circle", "heart.slash.circle.fill", "heart.text.square",
        "heart.text.square.fill", "bolt.heart", "bolt.heart.fill",
        "waveform.path.ecg", "waveform.path.ecg.rectangle",
        "waveform.path.ecg.rectangle.fill", "stethoscope", "stethoscope.circle",
        "stethoscope.circle.fill", "bandage", "bandage.fill",
        "cross", "cross.fill", "cross.circle", "cross.circle.fill",
        "pills", "pills.fill", "pills.circle", "pills.circle.fill",
        "cross.vial", "cross.vial.fill", "syringe", "syringe.fill",
        "medical.thermometer", "medical.thermometer.fill", "ivfluid.bag",
        "ivfluid.bag.fill", "facemask", "facemask.fill",
        "brain", "brain.head.profile", "lungs", "lungs.fill",
        "liver.fill", "stomach.fill", "allergens", "allergens.fill",
    ]

    // MARK: - Shapes
    static let shapesSymbols = [
        "circle", "circle.fill", "circle.slash", "circle.slash.fill",
        "circle.lefthalf.filled", "circle.righthalf.filled",
        "circle.tophalf.filled", "circle.bottomhalf.filled",
        "circle.inset.filled", "circle.dashed", "circle.dashed.inset.filled",
        "circle.dotted", "circle.dotted.circle", "circle.dotted.circle.fill",
        "circle.grid.2x2", "circle.grid.2x2.fill", "circle.grid.3x3",
        "circle.grid.3x3.fill", "circle.grid.cross", "circle.grid.cross.fill",
        "square", "square.fill", "square.slash", "square.slash.fill",
        "square.lefthalf.filled", "square.righthalf.filled",
        "square.tophalf.filled", "square.bottomhalf.filled",
        "square.inset.filled", "square.dashed", "square.dashed.inset.filled",
        "square.on.square", "square.fill.on.square.fill", "square.on.square.dashed",
        "square.on.circle", "square.fill.on.circle.fill",
        "square.grid.2x2", "square.grid.2x2.fill", "square.grid.3x2",
        "square.grid.3x2.fill", "square.grid.3x3", "square.grid.3x3.fill",
        "square.grid.3x3.topleft.filled", "square.grid.3x3.topmiddle.filled",
        "square.grid.3x3.topright.filled", "square.grid.3x3.middleleft.filled",
        "square.grid.3x3.middle.filled", "square.grid.3x3.middleright.filled",
        "square.grid.3x3.bottomleft.filled", "square.grid.3x3.bottommiddle.filled",
        "square.grid.3x3.bottomright.filled", "square.grid.4x3.fill",
        "rectangle", "rectangle.fill", "rectangle.slash", "rectangle.slash.fill",
        "rectangle.portrait", "rectangle.portrait.fill",
        "rectangle.portrait.slash", "rectangle.portrait.slash.fill",
        "triangle", "triangle.fill", "triangle.lefthalf.filled",
        "triangle.righthalf.filled", "triangle.tophalf.filled",
        "triangle.bottomhalf.filled", "triangle.inset.filled",
        "diamond", "diamond.fill", "diamond.lefthalf.filled",
        "diamond.righthalf.filled", "diamond.tophalf.filled",
        "diamond.bottomhalf.filled", "diamond.inset.filled",
        "octagon", "octagon.fill", "octagon.lefthalf.filled",
        "octagon.righthalf.filled", "octagon.tophalf.filled",
        "octagon.bottomhalf.filled", "hexagon", "hexagon.fill",
        "hexagon.lefthalf.filled", "hexagon.righthalf.filled",
        "hexagon.tophalf.filled", "hexagon.bottomhalf.filled",
        "pentagon", "pentagon.fill", "pentagon.lefthalf.filled",
        "pentagon.righthalf.filled", "pentagon.tophalf.filled",
        "pentagon.bottomhalf.filled", "star", "star.fill",
        "star.circle", "star.circle.fill", "star.square", "star.square.fill",
        "star.slash", "star.slash.fill", "star.leadinghalf.filled",
        "star.bubble", "star.bubble.fill", "capsule", "capsule.fill",
        "capsule.portrait", "capsule.portrait.fill", "oval", "oval.fill",
        "oval.portrait", "oval.portrait.fill", "seal", "seal.fill",
        "shield", "shield.fill", "shield.slash", "shield.slash.fill",
        "shield.lefthalf.filled", "shield.righthalf.filled",
        "shield.checkered", "rhombus", "rhombus.fill",
    ]

    // MARK: - Arrows
    static let arrowsSymbols = [
        "arrow.up", "arrow.up.circle", "arrow.up.circle.fill",
        "arrow.up.square", "arrow.up.square.fill", "arrow.down",
        "arrow.down.circle", "arrow.down.circle.fill", "arrow.down.square",
        "arrow.down.square.fill", "arrow.left", "arrow.left.circle",
        "arrow.left.circle.fill", "arrow.left.square", "arrow.left.square.fill",
        "arrow.right", "arrow.right.circle", "arrow.right.circle.fill",
        "arrow.right.square", "arrow.right.square.fill", "arrow.up.left",
        "arrow.up.left.circle", "arrow.up.left.circle.fill", "arrow.up.left.square",
        "arrow.up.left.square.fill", "arrow.up.right", "arrow.up.right.circle",
        "arrow.up.right.circle.fill", "arrow.up.right.square", "arrow.up.right.square.fill",
        "arrow.down.left", "arrow.down.left.circle", "arrow.down.left.circle.fill",
        "arrow.down.left.square", "arrow.down.left.square.fill", "arrow.down.right",
        "arrow.down.right.circle", "arrow.down.right.circle.fill", "arrow.down.right.square",
        "arrow.down.right.square.fill", "arrow.up.arrow.down", "arrow.up.arrow.down.circle",
        "arrow.up.arrow.down.circle.fill", "arrow.up.arrow.down.square", "arrow.up.arrow.down.square.fill",
        "arrow.left.arrow.right", "arrow.left.arrow.right.circle",
        "arrow.left.arrow.right.circle.fill", "arrow.left.arrow.right.square",
        "arrow.left.arrow.right.square.fill", "arrow.turn.down.left", "arrow.turn.down.right",
        "arrow.turn.up.left", "arrow.turn.up.right", "arrow.turn.right.up",
        "arrow.turn.right.down", "arrow.turn.left.up", "arrow.turn.left.down",
        "arrow.uturn.left", "arrow.uturn.left.circle", "arrow.uturn.left.circle.fill",
        "arrow.uturn.left.square", "arrow.uturn.left.square.fill",
        "arrow.uturn.right", "arrow.uturn.right.circle", "arrow.uturn.right.circle.fill",
        "arrow.uturn.right.square", "arrow.uturn.right.square.fill",
        "arrow.uturn.up", "arrow.uturn.up.circle", "arrow.uturn.up.circle.fill",
        "arrow.uturn.up.square", "arrow.uturn.up.square.fill",
        "arrow.uturn.down", "arrow.uturn.down.circle", "arrow.uturn.down.circle.fill",
        "arrow.uturn.down.square", "arrow.uturn.down.square.fill",
        "arrow.clockwise", "arrow.clockwise.circle", "arrow.clockwise.circle.fill",
        "arrow.counterclockwise", "arrow.counterclockwise.circle",
        "arrow.counterclockwise.circle.fill", "arrow.2.circlepath",
        "arrow.2.circlepath.circle", "arrow.2.circlepath.circle.fill",
        "arrow.triangle.2.circlepath", "arrow.triangle.2.circlepath.circle",
        "arrow.triangle.2.circlepath.circle.fill", "arrow.up.to.line",
        "arrow.up.to.line.circle", "arrow.up.to.line.circle.fill",
        "arrow.up.to.line.compact", "arrow.down.to.line", "arrow.down.to.line.circle",
        "arrow.down.to.line.circle.fill", "arrow.down.to.line.compact",
        "arrow.left.to.line", "arrow.left.to.line.circle", "arrow.left.to.line.circle.fill",
        "arrow.left.to.line.compact", "arrow.right.to.line", "arrow.right.to.line.circle",
        "arrow.right.to.line.circle.fill", "arrow.right.to.line.compact",
        "return", "return.left", "return.right", "arrow.up.and.down.and.arrow.left.and.right",
        "arrow.up.left.and.down.right.and.arrow.up.right.and.down.left",
        "arrow.3.trianglepath", "arrowshape.left", "arrowshape.left.fill",
        "arrowshape.right", "arrowshape.right.fill", "arrowshape.up",
        "arrowshape.up.fill", "arrowshape.down", "arrowshape.down.fill",
        "arrowshape.turn.up.left", "arrowshape.turn.up.left.fill",
        "arrowshape.turn.up.left.circle", "arrowshape.turn.up.left.circle.fill",
        "arrowshape.turn.up.right", "arrowshape.turn.up.right.fill",
        "arrowshape.turn.up.right.circle", "arrowshape.turn.up.right.circle.fill",
        "arrowshape.turn.up.left.2", "arrowshape.turn.up.left.2.fill",
        "arrowshape.turn.up.left.2.circle", "arrowshape.turn.up.left.2.circle.fill",
        "arrowshape.bounce.forward", "arrowshape.bounce.forward.fill",
        "arrowshape.bounce.right", "arrowshape.bounce.right.fill",
        "arrowshape.zigzag.forward", "arrowshape.zigzag.forward.fill",
        "arrowshape.zigzag.right", "arrowshape.zigzag.right.fill",
        "chevron.up", "chevron.up.circle", "chevron.up.circle.fill",
        "chevron.up.square", "chevron.up.square.fill", "chevron.down",
        "chevron.down.circle", "chevron.down.circle.fill", "chevron.down.square",
        "chevron.down.square.fill", "chevron.left", "chevron.left.circle",
        "chevron.left.circle.fill", "chevron.left.square", "chevron.left.square.fill",
        "chevron.right", "chevron.right.circle", "chevron.right.circle.fill",
        "chevron.right.square", "chevron.right.square.fill", "chevron.left.2",
        "chevron.right.2", "chevron.up.2", "chevron.down.2",
        "chevron.compact.up", "chevron.compact.down", "chevron.compact.left",
        "chevron.compact.right",
    ]

    // MARK: - Math
    static let mathSymbols = [
        "plus", "plus.circle", "plus.circle.fill", "plus.square",
        "plus.square.fill", "plus.rectangle", "plus.rectangle.fill",
        "plus.diamond", "plus.diamond.fill", "minus", "minus.circle",
        "minus.circle.fill", "minus.square", "minus.square.fill",
        "minus.rectangle", "minus.rectangle.fill", "minus.diamond",
        "minus.diamond.fill", "multiply", "multiply.circle", "multiply.circle.fill",
        "multiply.square", "multiply.square.fill", "divide", "divide.circle",
        "divide.circle.fill", "divide.square", "divide.square.fill",
        "equal", "equal.circle", "equal.circle.fill", "equal.square",
        "equal.square.fill", "lessthan", "lessthan.circle", "lessthan.circle.fill",
        "lessthan.square", "lessthan.square.fill", "greaterthan",
        "greaterthan.circle", "greaterthan.circle.fill", "greaterthan.square",
        "greaterthan.square.fill", "number", "number.circle", "number.circle.fill",
        "number.square", "number.square.fill", "xmark", "xmark.circle",
        "xmark.circle.fill", "xmark.square", "xmark.square.fill",
        "xmark.rectangle", "xmark.rectangle.fill", "xmark.diamond",
        "xmark.diamond.fill", "xmark.shield", "xmark.shield.fill",
        "xmark.octagon", "xmark.octagon.fill", "checkmark", "checkmark.circle",
        "checkmark.circle.fill", "checkmark.circle.trianglebadge.exclamationmark",
        "checkmark.square", "checkmark.square.fill", "checkmark.rectangle",
        "checkmark.rectangle.fill", "checkmark.diamond", "checkmark.diamond.fill",
        "checkmark.shield", "checkmark.shield.fill", "questionmark",
        "questionmark.circle", "questionmark.circle.fill", "questionmark.square",
        "questionmark.square.fill", "questionmark.diamond", "questionmark.diamond.fill",
        "exclamationmark", "exclamationmark.circle", "exclamationmark.circle.fill",
        "exclamationmark.square", "exclamationmark.square.fill",
        "exclamationmark.triangle", "exclamationmark.triangle.fill",
        "exclamationmark.octagon", "exclamationmark.octagon.fill",
        "exclamationmark.shield", "exclamationmark.shield.fill",
        "exclamationmark.2", "exclamationmark.3", "sum", "percent",
        "function", "fx", "x.squareroot", "ellipsis", "ellipsis.circle",
        "ellipsis.circle.fill", "ellipsis.rectangle", "ellipsis.rectangle.fill",
        "ellipsis.vertical.bubble", "ellipsis.vertical.bubble.fill",
    ]

    // MARK: - Privacy & Security
    static let privacySymbols = [
        "lock", "lock.fill", "lock.circle", "lock.circle.fill",
        "lock.square", "lock.square.fill", "lock.square.stack", "lock.square.stack.fill",
        "lock.rectangle", "lock.rectangle.fill", "lock.rectangle.stack",
        "lock.rectangle.stack.fill", "lock.rectangle.on.rectangle",
        "lock.rectangle.on.rectangle.fill", "lock.shield", "lock.shield.fill",
        "lock.slash", "lock.slash.fill", "lock.open", "lock.open.fill",
        "lock.open.trianglebadge.exclamationmark", "lock.open.trianglebadge.exclamationmark.fill",
        "key", "key.fill", "key.radiowaves.forward", "key.radiowaves.forward.fill",
        "key.horizontal", "key.horizontal.fill", "key.viewfinder",
        "lock.badge.clock", "lock.badge.clock.fill", "shield", "shield.fill",
        "shield.lefthalf.filled", "shield.righthalf.filled",
        "shield.slash", "shield.slash.fill", "shield.checkered",
        "checkmark.shield", "checkmark.shield.fill", "xmark.shield", "xmark.shield.fill",
        "exclamationmark.shield", "exclamationmark.shield.fill",
        "faceid", "touchid", "opticid", "person.badge.shield.checkmark",
        "person.badge.shield.checkmark.fill", "person.badge.key", "person.badge.key.fill",
        "hand.raised", "hand.raised.fill", "hand.raised.circle", "hand.raised.circle.fill",
        "hand.raised.square", "hand.raised.square.fill", "hand.raised.slash",
        "hand.raised.slash.fill", "eye.slash", "eye.slash.fill", "eye.slash.circle",
        "eye.slash.circle.fill", "eye.trianglebadge.exclamationmark",
        "eye.trianglebadge.exclamationmark.fill",
    ]

    // MARK: - Home
    static let homeSymbols = [
        "house", "house.fill", "house.circle", "house.circle.fill",
        "house.lodge", "house.lodge.fill", "house.lodge.circle", "house.lodge.circle.fill",
        "music.note.house", "music.note.house.fill", "building", "building.fill",
        "building.2", "building.2.fill", "building.2.crop.circle",
        "building.2.crop.circle.fill", "lightbulb", "lightbulb.fill",
        "lightbulb.circle", "lightbulb.circle.fill", "lightbulb.slash",
        "lightbulb.slash.fill", "lightbulb.led", "lightbulb.led.fill",
        "lightbulb.led.wide", "lightbulb.led.wide.fill", "lightbulb.min",
        "lightbulb.min.fill", "lightbulb.max", "lightbulb.max.fill",
        "fanblades", "fanblades.fill", "fan", "fan.fill",
        "fan.ceiling", "fan.ceiling.fill", "fan.desk", "fan.desk.fill",
        "fan.floor", "fan.floor.fill", "lamp.desk", "lamp.desk.fill",
        "lamp.table", "lamp.table.fill", "lamp.floor", "lamp.floor.fill",
        "lamp.ceiling", "lamp.ceiling.fill", "lamp.ceiling.inverse",
        "chandelier", "chandelier.fill", "lightswitch.on", "lightswitch.on.fill",
        "lightswitch.on.square", "lightswitch.on.square.fill", "lightswitch.off",
        "lightswitch.off.fill", "lightswitch.off.square", "lightswitch.off.square.fill",
        "poweroutlet.type.a", "poweroutlet.type.a.fill", "poweroutlet.type.a.square",
        "poweroutlet.type.a.square.fill", "poweroutlet.type.b", "poweroutlet.type.b.fill",
        "poweroutlet.type.b.square", "poweroutlet.type.b.square.fill",
        "poweroutlet.type.c", "poweroutlet.type.c.fill", "poweroutlet.type.c.square",
        "poweroutlet.type.c.square.fill", "poweroutlet.type.e", "poweroutlet.type.e.fill",
        "poweroutlet.type.e.square", "poweroutlet.type.e.square.fill",
        "poweroutlet.type.f", "poweroutlet.type.f.fill", "poweroutlet.type.f.square",
        "poweroutlet.type.f.square.fill", "poweroutlet.type.g", "poweroutlet.type.g.fill",
        "poweroutlet.type.g.square", "poweroutlet.type.g.square.fill",
        "poweroutlet.type.h", "poweroutlet.type.h.fill", "poweroutlet.type.h.square",
        "poweroutlet.type.h.square.fill", "poweroutlet.type.i", "poweroutlet.type.i.fill",
        "poweroutlet.type.i.square", "poweroutlet.type.i.square.fill",
        "poweroutlet.type.j", "poweroutlet.type.j.fill", "poweroutlet.type.j.square",
        "poweroutlet.type.j.square.fill", "poweroutlet.type.k", "poweroutlet.type.k.fill",
        "poweroutlet.type.k.square", "poweroutlet.type.k.square.fill",
        "poweroutlet.type.l", "poweroutlet.type.l.fill", "poweroutlet.type.l.square",
        "poweroutlet.type.l.square.fill",
        "door.left.hand.open", "door.left.hand.closed", "door.right.hand.open",
        "door.right.hand.closed", "door.sliding.left.hand.open", "door.sliding.left.hand.closed",
        "door.sliding.right.hand.open", "door.sliding.right.hand.closed",
        "door.garage.open", "door.garage.closed", "door.garage.double.bay.open",
        "door.garage.double.bay.closed", "door.french.open", "door.french.closed",
        "window.vertical.open", "window.vertical.closed", "window.horizontal",
        "window.horizontal.closed", "window.ceiling", "window.ceiling.closed",
        "window.awning", "window.awning.closed", "window.casement",
        "window.casement.closed", "spigot", "spigot.fill", "shower", "shower.fill",
        "shower.sidejet", "shower.sidejet.fill", "shower.handheld",
        "shower.handheld.fill", "bathtub", "bathtub.fill", "sink", "sink.fill",
        "toilet", "toilet.fill", "bed.double", "bed.double.fill",
        "bed.double.circle", "bed.double.circle.fill", "sofa", "sofa.fill",
        "chair", "chair.fill", "chair.lounge", "chair.lounge.fill",
        "table.furniture", "table.furniture.fill", "washer", "washer.fill",
        "dryer", "dryer.fill", "dishwasher", "dishwasher.fill",
        "oven", "oven.fill", "cooktop", "cooktop.fill",
        "refrigerator", "refrigerator.fill", "microwave", "microwave.fill",
    ]

    // MARK: - Fitness
    static let fitnessSymbols = [
        "figure.walk", "figure.walk.circle", "figure.walk.circle.fill",
        "figure.walk.diamond", "figure.walk.diamond.fill", "figure.walk.arrival",
        "figure.walk.departure", "figure.walk.motion", "figure.run", "figure.run.circle",
        "figure.run.circle.fill", "figure.dance", "figure.roll", "figure.roll.runningpace",
        "figure.stand", "figure.stand.line.dotted.figure.stand", "figure.american.football",
        "figure.archery", "figure.australian.football", "figure.badminton",
        "figure.barre", "figure.baseball", "figure.basketball", "figure.bowling",
        "figure.boxing", "figure.climbing", "figure.cooldown", "figure.core.training",
        "figure.cricket", "figure.cross.training", "figure.curling", "figure.disc.sports",
        "figure.elliptical", "figure.equestrian.sports", "figure.fencing",
        "figure.fishing", "figure.flexibility", "figure.golf", "figure.gymnastics",
        "figure.hand.cycling", "figure.handball", "figure.highintensity.intervaltraining",
        "figure.hiking", "figure.hockey", "figure.hunting", "figure.indoor.cycle",
        "figure.jumprope", "figure.kickboxing", "figure.lacrosse", "figure.martial.arts",
        "figure.mind.and.body", "figure.mixed.cardio", "figure.open.water.swim",
        "figure.outdoor.cycle", "figure.pickleball", "figure.pilates", "figure.play",
        "figure.pool.swim", "figure.racquetball", "figure.rolling", "figure.rower",
        "figure.rugby", "figure.sailing", "figure.skating", "figure.skiing.crosscountry",
        "figure.skiing.downhill", "figure.snowboarding", "figure.soccer",
        "figure.socialdance", "figure.softball", "figure.squash", "figure.stair.stepper",
        "figure.stairs", "figure.step.training", "figure.surfing", "figure.table.tennis",
        "figure.taichi", "figure.tennis", "figure.track.and.field", "figure.volleyball",
        "figure.water.fitness", "figure.waterpolo", "figure.wave", "figure.wrestling",
        "figure.yoga", "dumbbell", "dumbbell.fill", "sportscourt", "sportscourt.fill",
        "sportscourt.circle", "sportscourt.circle.fill", "soccerball",
        "soccerball.inverse", "baseball", "baseball.fill", "basketball", "basketball.fill",
        "football", "football.fill", "volleyball", "volleyball.fill",
        "tennis.racket", "tennis.racket.circle", "tennis.racket.circle.fill",
        "tennisball", "tennisball.fill", "cricket.ball", "cricket.ball.fill",
        "hockey.puck", "hockey.puck.fill", "ski.fill", "skis", "skis.fill",
        "snowboard", "snowboard.fill", "skateboard", "skateboard.fill",
        "surfboard", "surfboard.fill", "medal", "medal.fill",
        "trophy", "trophy.fill", "trophy.circle", "trophy.circle.fill",
        "rosette", "target", "flag.checkered", "flag.checkered.circle",
        "flag.checkered.circle.fill", "flag.checkered.2.crossed",
    ]

    // MARK: - Accessibility
    static let accessibilitySymbols = [
        "accessibility", "accessibility.fill", "accessibility.badge.arrow.up.right",
        "figure.roll", "figure.roll.runningpace", "figure.wave",
        "figure.wave.circle", "figure.wave.circle.fill", "ear",
        "ear.badge.checkmark", "ear.trianglebadge.exclamationmark", "ear.and.waveform",
        "ear.fill", "hearingdevice.ear", "hearingdevice.ear.fill",
        "hearingdevice.and.signal.meter", "hearingdevice.and.signal.meter.fill",
        "hand.point.up.braille", "hand.point.up.braille.fill",
        "character.bubble", "character.bubble.fill", "character.cursor.ibeam",
        "character.textbox", "textformat.size", "textformat.size.smaller",
        "textformat.size.larger", "character.book.closed", "character.book.closed.fill",
        "eye.slash", "eye.slash.fill", "eye.slash.circle", "eye.slash.circle.fill",
        "eye.trianglebadge.exclamationmark", "eye.trianglebadge.exclamationmark.fill",
    ]

    // MARK: - Indices
    static let indicesSymbols = [
        "0.circle", "0.circle.fill", "0.square", "0.square.fill",
        "1.circle", "1.circle.fill", "1.square", "1.square.fill",
        "2.circle", "2.circle.fill", "2.square", "2.square.fill",
        "3.circle", "3.circle.fill", "3.square", "3.square.fill",
        "4.circle", "4.circle.fill", "4.square", "4.square.fill",
        "5.circle", "5.circle.fill", "5.square", "5.square.fill",
        "6.circle", "6.circle.fill", "6.square", "6.square.fill",
        "7.circle", "7.circle.fill", "7.square", "7.square.fill",
        "8.circle", "8.circle.fill", "8.square", "8.square.fill",
        "9.circle", "9.circle.fill", "9.square", "9.square.fill",
        "10.circle", "10.circle.fill", "10.square", "10.square.fill",
        "a.circle", "a.circle.fill", "a.square", "a.square.fill",
        "b.circle", "b.circle.fill", "b.square", "b.square.fill",
        "c.circle", "c.circle.fill", "c.square", "c.square.fill",
        "d.circle", "d.circle.fill", "d.square", "d.square.fill",
        "e.circle", "e.circle.fill", "e.square", "e.square.fill",
        "f.circle", "f.circle.fill", "f.square", "f.square.fill",
        "g.circle", "g.circle.fill", "g.square", "g.square.fill",
        "h.circle", "h.circle.fill", "h.square", "h.square.fill",
        "i.circle", "i.circle.fill", "i.square", "i.square.fill",
        "j.circle", "j.circle.fill", "j.square", "j.square.fill",
        "k.circle", "k.circle.fill", "k.square", "k.square.fill",
        "l.circle", "l.circle.fill", "l.square", "l.square.fill",
        "m.circle", "m.circle.fill", "m.square", "m.square.fill",
        "n.circle", "n.circle.fill", "n.square", "n.square.fill",
        "o.circle", "o.circle.fill", "o.square", "o.square.fill",
        "p.circle", "p.circle.fill", "p.square", "p.square.fill",
        "q.circle", "q.circle.fill", "q.square", "q.square.fill",
        "r.circle", "r.circle.fill", "r.square", "r.square.fill",
        "s.circle", "s.circle.fill", "s.square", "s.square.fill",
        "t.circle", "t.circle.fill", "t.square", "t.square.fill",
        "u.circle", "u.circle.fill", "u.square", "u.square.fill",
        "v.circle", "v.circle.fill", "v.square", "v.square.fill",
        "w.circle", "w.circle.fill", "w.square", "w.square.fill",
        "x.circle", "x.circle.fill", "x.square", "x.square.fill",
        "y.circle", "y.circle.fill", "y.square", "y.square.fill",
        "z.circle", "z.circle.fill", "z.square", "z.square.fill",
    ]
}
